import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type { Database } from './client.js';
import { ConnectionError, mapPostgresError } from './errors.js';

export interface RunMigrationsOptions {
  /** Folder containing the SQL migration files generated by `drizzle-kit generate`. */
  migrationsFolder: string;
  /**
   * How many times to retry if the database isn't accepting connections yet.
   * Useful in Docker/Kubernetes where the app container can start before the
   * database container is ready to accept connections. Defaults to 5.
   */
  maxRetries?: number;
  /** Delay between connection retries, in ms. Defaults to 2000. */
  retryDelayMs?: number;
  onRetry?: (attempt: number, maxRetries: number, error: unknown) => void;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Applies pending SQL migrations. Intended to be run once at deploy/startup
 * time (a Docker entrypoint step or a Kubernetes init container) — not on
 * every app boot in a horizontally-scaled deployment, since concurrent
 * instances all running migrations simultaneously would race on the same
 * migration lock table. `drizzle-orm`'s migrator takes an advisory lock
 * internally, so concurrent callers serialize safely rather than corrupt
 * state, but only one should typically be responsible for it.
 */
export async function runMigrations(
  db: Database,
  options: RunMigrationsOptions,
): Promise<void> {
  const maxRetries = options.maxRetries ?? 5;
  const retryDelayMs = options.retryDelayMs ?? 2_000;

  let attempt = 0;
  for (;;) {
    try {
      await migrate(db, { migrationsFolder: options.migrationsFolder });
      return;
    } catch (rawError) {
      const error = mapPostgresError(rawError);
      const isConnectivityIssue = error instanceof ConnectionError;

      if (!isConnectivityIssue || attempt >= maxRetries) {
        throw error;
      }

      attempt += 1;
      options.onRetry?.(attempt, maxRetries, error);
      await sleep(retryDelayMs);
    }
  }
}
